name: murmur
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter_skill: ^0.2.6
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_soloud: 4.0.3
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.5
  audio_service: ^0.18.17
  audioplayers: ^6.0.0
  in_app_purchase: ^3.2.0
  nsd: ^5.0.1
  cryptography: ^2.7.0
  health: ^13.3.1
  quick_actions: ^1.0.10
  url_launcher: ^6.3.2
  google_fonts: ^8.1.0
  record: ^6.2.0
  fftea: ^1.1.0
  spake2plus: ^1.0.0
  in_app_review: ^2.0.11
  in_app_update: ^4.2.5
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/agent_card.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0D0F14"
  image: "assets/icon.png"
  android_12:
    image: "assets/icon.png"
    color: "#0D0F14"
  fullscreen: true
